### ISSUE TITLE
Increase character limit of the Debriefing fields

### ISSUE THREAD

**Issue by sanjaymucharla** [code-for-india/projectKHEL#17]
The debriefing field are currently not taking anything beyond 100 characters. Could you please make this as paragraph fields. Debriefing sometimes are long summaries.

**Comment by rahulsh1** [comment]
You now get a multi-line text to enter the data. What do you mean by Paragraph fields? I can update it to support 500 characters.

**Comment by rahulsh1** [comment]
Fixed
