### ISSUE TITLE
Sorting names in app

### ISSUE THREAD

**Issue by sanjaymucharla** [code-for-india/projectKHEL#18]
In the app, after the location and when you click on beneficiaries, a list comes up with Name Class Age Sex of the child. Can we please sort the list first based on class and then name (A -> Z)? Also we just want to be able to see the name and class of the child. Dont require age and sex in the app under beneficiary details. Something in this format works. For example: Sanjay (10), which means Sanjay from Class 10.

**Comment by rahulsh1** [comment]
Will there always be a class for every child?
