### ISSUE TITLE
Export data to CSV

### ISSUE THREAD

**Issue by sanjaymucharla** [code-for-india/projectKHEL#7]
We would like to have a feature to download data to CSV files in each of the tabs (Locations, Modules, etc)

**Comment by rahulsh1** [comment]
You could use PhpMyAdmin directly to export data. You can export all in one go. You can even choose which columns you need.

**Comment by sanjaymucharla** [comment]
Has the database and all been set up? Not sure of the conversations you had with Raj. So asking.

If yes, please let me know all the info I would need to set up PhpMyAdmin
