### ISSUE TITLE
Debriefing

### ISSUE THREAD

**Issue by sanjaymucharla** [code-for-india/projectKHEL#9]
Add a new field category called 'Debriefing', under which there will be 3 big text boxes that should support paragraphs), by the names
- What worked?
- What can be improved?
- What didn't work?

**Comment by rahulsh1** [comment]
Should this replace the Comments field then? This is already capturing more info about the session

**Comment by sanjaymucharla** [comment]
No. Don't replace. Just add this new category. The reason we are asking for these additional 3 fields is because we have started measuring our performance based on these 3 feedback areas provided by coordinators.

The comments field should remain as it is, where they would add any additional notes if required.

**Comment by rahulsh1** [comment]
Added in ec0f1bbe2211f26f9de085d9082bf1b814260c61
